/**
 * Generated by `scripts/build-rank-cards.mjs` — do not edit by hand.
 *
 * What the app needs to know about each card's art: where to find it, and
 * where that card puts its row of result squares. The row is not in the same
 * place on every rank — a longer subline pushes it down — so this is measured
 * from the Figma export at build time rather than written down.
 *
 * Rank *copy* is not here. The words on the cards live in `copy.ts`.
 */

export interface RankArt {
  art: string
  /** Top edge of the squares row, in the card's 360×180 units. */
  squaresY: number
}

export const RANK_ART: Record<number, RankArt | undefined> = {
  1: { art: "/rankCards/rank-1.png", squaresY: 118 },
  2: { art: "/rankCards/rank-2.png", squaresY: 124 },
  3: { art: "/rankCards/rank-3.png", squaresY: 125 },
  4: { art: "/rankCards/rank-4.png", squaresY: 118 },
  5: { art: "/rankCards/rank-5.png", squaresY: 118 },
}
